//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypto_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebruiker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gebruiker()
        {
            this.GebruikerFiles = new HashSet<GebruikerFile>();
        }
    
        public int Id { get; set; }
        public string Gebruikersnaam { get; set; }
        public string Paswoord { get; set; }
        public string Naam { get; set; }
        public string Voornaam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GebruikerFile> GebruikerFiles { get; set; }
    }
}
