//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypto_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class GebruikerFile
    {
        public int FileId { get; set; }
        public Nullable<int> gebruikersId { get; set; }
    
        public virtual Gebruiker Gebruiker { get; set; }
    }
}
