USE [master]
GO

/****** Object:  Database [BS12]    Script Date: 12/05/2016 10:12:37 ******/
DROP DATABASE [BS12]
GO

/****** Object:  Database [BS12]    Script Date: 12/05/2016 10:12:37 ******/
CREATE DATABASE [BS12]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BS12', FILENAME = N'C:\Users\11400919\BS12.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BS12_log', FILENAME = N'C:\Users\11400919\BS12_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BS12] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BS12].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BS12] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BS12] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BS12] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BS12] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BS12] SET ARITHABORT OFF 
GO

ALTER DATABASE [BS12] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BS12] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BS12] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BS12] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BS12] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BS12] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BS12] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BS12] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BS12] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BS12] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BS12] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BS12] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BS12] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BS12] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BS12] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BS12] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BS12] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BS12] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BS12] SET  MULTI_USER 
GO

ALTER DATABASE [BS12] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BS12] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BS12] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BS12] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BS12] SET  READ_WRITE 
GO


